### ISSUE TITLE
endless loop while compiling

### ISSUE THREAD

**Issue by AdrianV** [R32/no-vdom#1]
Hi,
I have this html stored in setup.html

		<div id="setup" data-page="setup" class="page navbar-fixed">
			<div class="navbar" data-enhance="false">
				<div class="navbar-inner">
					<div class="left"><a href="#start" class="link icon-only"><i class="icon icon-back"></i></a></div>
					<div class="center" i18n-txt="setup-title">Server Setup</div>
				</div>
			</div>
			
			<div data-role="content" class="page-content">
				<div class="list-block">
					<ul>
						<li>
							<div class="item-content">
								<div class="item-inner">
									<div class="item-title item-title-show" i18n-txt="setup-server">Server</div>
									<div class="item-input">
										<input type="text" id="setup-inp-server" value="" class="setup-inp-server" />
									</div>
								</div>
							</div>
						</li>
						<li>
							<div class="item-content">
								<div class="item-inner">
									<div class="item-title item-title-show" i18n-txt="setup-tel">Tel Nr.</div>
									<div class="item-input">
										<input type="tel" id="setup-inp-phone" value="" class="setup-inp-phone" />
									</div>
								</div>
							</div>
						</li>
						<li>
							<div class="item-content">
								<div class="item-inner">
									<div class="item-title item-title-show" i18n-txt="setup-activation">Code</div>
									<div class="item-input">
										<input type="text" id="setup-inp-activation" value="" class="setup-inp-activation" />
									</div>
								</div>
							</div>
						</li>
					</ul>
				</div>
				<div class="content-block">
					<p class="button-row">
						<a id="setup-done" class="button button-big button-fill color-green" i18n-txt="setup-ok">OK</a>					
					</p>						
					<p class="button-row">
						<a id="setup-test" class="button button-big button-fill color-green" i18n-txt="setup-test">Verbindungstest</a>					
					</p>						
				</div>
				<div class="content-block">
					<div id="setup-info"></div>
					<div id="info"></div>
				</div>
			</div>
		</div>

and I try this:

	@:build(Nvd.build("setup.html", ".page-content",{
		inp_server: Prop('input.setup-inp-server', "value"),
		inp_phone: Prop('input.setup-inp-phone', "value"),
		inp_activation: Prop('input.setup-inp-activation', "value"),
	} )) abstract SetupHtml(nvd.Comp) {

	}

when I compile I run into an endless loop.
I used ".page-content" because "div" finds the wrong div = div.navbar and it should find div.page
using #setup does not work either
it looks like the first node is ignored

**Comment by R32** [comment]
This is because when `csss`  is start to quering, The first element will become the root node of the query.  and the query starts from its child elements, not beginning from itself.

for example:
```html
<div class="hi">
    <div class="hi there"></div>
</div>
```
This example can be run in the chrome console
```js
var root = document.querySelector(".hi");  // now the ".hi" is the root
root.querySelector(".hi");                 // this will return "hi there" div
```
so you should not put the HTML fragment as the root of XML.

**Comment by AdrianV** [comment]
thanks - works now.
